_target_: sinusoidal_gradient_descent.eval.estimator.evaluation_loop
use_global_amp: true
saturate_global_amp: false # Should be linked with `param_sampler.invert_sigmoid`
normalise_complex_grads: false

mode: multi
